<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">

  <xacro:property name="M_PI" value="3.14159"/>

  <xacro:property name="base_height" value="0.043" />
  <xacro:property name="base_radius" value="0.048" />
  <xacro:property name="link1_height" value="0.006" />
  <xacro:property name="link1_radius" value="0.048" />
  <xacro:property name="link2_offset" value="0.022" />
  <xacro:property name="link2_length" value="0.14605" />
  <xacro:property name="link3_length" value="0.187325" />
  <xacro:property name="link4_length" value="0.032" />
  <xacro:property name="gripper_offset" value="0.016" />

  <xacro:macro name="lynxmotion_al5d" params="prefix parent_link rate:=50 *origin">
    <!-- attach -->
    <joint name="arm_base_joint" type="fixed">
      <xacro:insert_block name="origin" />
      <parent link="${parent_link}"/>
      <child link="${prefix}base_link" />
    </joint>
    <!-- links -->
    <link name="${prefix}base_link">
      <visual>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${base_height}" radius="${base_radius}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <inertial>
        <mass value="1"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.0027" ixy="0" ixz="0" iyy="0.0027" iyz="0" izz="0.005" />
      </inertial>
      <collision>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${base_height}" radius="${link1_radius}"/>
        </geometry>
      </collision>
    </link>
    <link name="${prefix}link_1">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${link1_height}" radius="${link1_radius}"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <inertial>
        <mass value="1"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.0027" ixy="0" ixz="0" iyy="0.0027" iyz="0" izz="0.005" />
      </inertial>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
           <cylinder length="${link1_height}" radius="${base_radius}"/>
        </geometry>
      </collision>
    </link>
    <link name="${prefix}link_2">
      <visual>
        <origin xyz="${link2_length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${link2_length-0.02} 0.02 .02"/>
        </geometry>
        <material name="silver">
          <color rgba="0.8 0.8 0.8 1"/>
        </material>
      </visual>
      <inertial>
        <mass value="1"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.0027" ixy="0" ixz="0" iyy="0.0027" iyz="0" izz="0.005" />
      </inertial>
      <collision>
        <origin xyz="${link2_length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${link2_length-0.02} 0.02 .02"/>
        </geometry>
      </collision>
    </link>
    <link name="${prefix}link_3">
      <visual>
        <origin xyz="${link3_length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${link3_length-0.02} 0.02 0.02"/>
        </geometry>
        <material name="silver">
          <color rgba="0.8 0.8 0.8 1"/>
        </material>
      </visual>
      <inertial>
        <mass value="1"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.0027" ixy="0" ixz="0" iyy="0.0027" iyz="0" izz="0.005" />
      </inertial>
      <collision>
        <origin xyz="${link3_length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${link3_length} 0.02 0.02"/>
        </geometry>
      </collision>
    </link>
    <link name="${prefix}link_4">
      <visual>
        <origin xyz="${link4_length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${link4_length} 0.02 0.02"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <inertial>
        <mass value="1"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.0027" ixy="0" ixz="0" iyy="0.0027" iyz="0" izz="0.005" />
      </inertial>
      <collision>
        <origin xyz="${link4_length/2} 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="${link4_length} 0.02 0.02"/>
        </geometry>
      </collision>
    </link>
    <link name="${prefix}gripper">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.05 0.05 0.05"/>
        </geometry>
        <material name="black">
          <color rgba="0 0 0 1"/>
        </material>
      </visual>
      <inertial>
        <mass value="1"/>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <inertia ixx="0.0027" ixy="0" ixz="0" iyy="0.0027" iyz="0" izz="0.005" />
      </inertial>
      <collision>
        <origin xyz="0 0 0.025" rpy="0 0 0"/>
        <geometry>
          <box size="0.05 0.05 0.05"/>
        </geometry>
      </collision>
    </link>

    <!-- joints -->
    <joint name="${prefix}joint_1" type="revolute">
      <origin xyz="0 0 ${base_height + link1_height}" rpy="0 0 0"/>
      <parent link="${prefix}base_link"/>
      <child link="${prefix}link_1"/>
      <axis xyz="0 0 1"/>
      <limit lower="-${M_PI/2}" upper="${M_PI/2}" effort="0" velocity="3.67"/>
    </joint>
    <joint name="${prefix}joint_2" type="revolute">
      <origin xyz="0 0 ${link2_offset}" rpy="${M_PI/2} 0 0"/>
      <parent link="${prefix}link_1"/>
      <child link="${prefix}link_2"/>
      <axis xyz="0 0 1"/>
      <limit lower="-${M_PI/2}" upper="${M_PI/2}" effort="0" velocity="3.32"/>
    </joint>
    <joint name="${prefix}joint_3" type="revolute">
      <origin xyz="${link2_length} 0 0" rpy="0 0 0" />
      <parent link="${prefix}link_2"/>
      <child link="${prefix}link_3"/>
      <axis xyz="0 0 1"/>
      <limit lower="-${M_PI/2}" upper="${M_PI/2}" effort="0" velocity="3.67"/>
    </joint>
    <joint name="${prefix}joint_4" type="revolute">
      <origin xyz="${link3_length} 0 0" rpy="0 0 0"/>
      <parent link="${prefix}link_3"/>
      <child link="${prefix}link_4"/>
      <axis xyz="0 0 1"/>
      <limit lower="-${M_PI/2}" upper="${M_PI/2}" effort="0" velocity="6.98"/>
    </joint>
    <joint name="${prefix}gripper" type="revolute">
      <origin xyz="${link4_length + gripper_offset} 0 0" rpy="0 0 0"/>
      <parent link="${prefix}link_4"/>
      <child link="${prefix}gripper"/>
      <axis xyz="1 0 0"/>
      <limit lower="-${M_PI/2}" upper="${M_PI/2}" effort="0" velocity="6.98"/>
    </joint>

    <transmission name="${prefix}joint_1">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}joint_1">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="motor1">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
    <transmission name="${prefix}joint_2">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}joint_2">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="motor2">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
    <transmission name="${prefix}joint_3">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}joint_3">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="motor3">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
    <transmission name="${prefix}joint_4">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}joint_4">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="motor4">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
    <transmission name="${prefix}gripper">
      <type>transmission_interface/SimpleTransmission</type>
      <joint name="${prefix}gripper">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
      </joint>
      <actuator name="motor5">
        <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
        <mechanicalReduction>1</mechanicalReduction>
      </actuator>
    </transmission>
    <gazebo>
      <plugin name="control" filename="libgazebo_ros_control.so"/>
      <plugin name="joint_state_publisher" filename="libgazebo_ros_joint_state_publisher.so">
        <jointName>${prefix}joint_1, ${prefix}joint_2, ${prefix}joint_3, ${prefix}joint_4, ${prefix}gripper</jointName>
        <updateRate>${rate}</updateRate>
      </plugin>
    </gazebo>
  </xacro:macro>
</robot>
