# joint_limits.yaml allows the dynamics properties specified in the URDF to be overwritten or augmented as needed
# Specific joint properties can be changed with the keys [max_position, min_position, max_velocity, max_acceleration]
# Joint limits can be turned off with [has_velocity_limits, has_acceleration_limits]
joint_limits:
  al5d_gripper:
    has_velocity_limits: true
    max_velocity: 6.98
    has_acceleration_limits: false
    max_acceleration: 0
  al5d_joint_1:
    has_velocity_limits: true
    max_velocity: 3.67
    has_acceleration_limits: false
    max_acceleration: 0
  al5d_joint_2:
    has_velocity_limits: true
    max_velocity: 3.32
    has_acceleration_limits: false
    max_acceleration: 0
  al5d_joint_3:
    has_velocity_limits: true
    max_velocity: 3.67
    has_acceleration_limits: false
    max_acceleration: 0
  al5d_joint_4:
    has_velocity_limits: true
    max_velocity: 6.98
    has_acceleration_limits: false
    max_acceleration: 0